import Footer from "../components/Footer";
import NavBar from "../components/NavBar";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={montserrat.className}>
        <main
          className={`${montserrat.variable} font-mont bg-light w-full min-h-screen`}
        >
          <NavBar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
